<?php

namespace AppBundle\Repository;

/**
 * AtributoMLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoMLRepository extends \Doctrine\ORM\EntityRepository
{
}
