<?php

namespace AppBundle\Repository;

/**
 * BusquedaMLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusquedaMLRepository extends \Doctrine\ORM\EntityRepository
{
}
