<?php

namespace AppBundle\Repository;
use AppBundle\Entity\BusquedaEbay;

/**
 * BusquedaEbayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusquedaEbayRepository extends \Doctrine\ORM\EntityRepository
{
	public function selectMaxId() {
		return $this->getEntityManager()->createQueryBuilder()
			    ->select('MAX(e.id)')
			    ->from(BusquedaEbay::ORM_ENTITY, 'e')
			    ->getQuery()
			    ->getSingleScalarResult();

	}
}
