<?php

namespace AppBundle\Repository;

/**
 * BusquedaEbayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusquedaEbayRepository extends \Doctrine\ORM\EntityRepository
{
}
