<?php

namespace AppBundle\Repository;

/**
 * CargaImportacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargaImportacionRepository extends \Doctrine\ORM\EntityRepository
{
}
