<?php

namespace AppBundle\Repository;

/**
 * CategoriaMLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaMLRepository extends \Doctrine\ORM\EntityRepository
{
}
