<?php

namespace AppBundle\Repository;

/**
 * CategoriaEbayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaEbayRepository extends \Doctrine\ORM\EntityRepository
{
}
