<?php

namespace AppBundle\Repository;

/**
 * EntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
