<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EspecificacionesProductoEbay;

/**
 * EspecificacionesProductoEbayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecificacionesProductoEbayRepository extends \Doctrine\ORM\EntityRepository
{
	public function selectMaxId() {
		return $this->getEntityManager()->createQueryBuilder()
			    ->select('MAX(e.id)')
			    ->from(EspecificacionesProductoEbay::ORM_ENTITY, 'e')
			    ->getQuery()
			    ->getSingleScalarResult();

	}

	public function tieneRelacionConPublicacionId($especificacionId, $publicacionId) {

		$stmt =$this->getEntityManager()
					->getConnection()
					->prepare("select * from publicaciones_espeficaciciones_ebay where publicacion_ebay_id = '".$publicacionId."' and especificaciones_producto_ebay_id = '" .$especificacionId. "';");
		$stmt->execute();
		return count($stmt->fetchAll()) > 0;
	}
	
}
