<?php

namespace AppBundle\Repository;

/**
 * OrdenDeCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDeCompraRepository extends \Doctrine\ORM\EntityRepository
{
}
