<?php

namespace AppBundle\Repository;

/**
 * PublicacionPropiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionPropiaRepository extends \Doctrine\ORM\EntityRepository
{
}
