<?php

namespace AppBundle\Repository;

/**
 * PublicacionMLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionMLRepository extends \Doctrine\ORM\EntityRepository
{
}
