<?php

namespace AppBundle\Repository;

/**
 * PublicacionMLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionMLRepository extends \Doctrine\ORM\EntityRepository
{
	public function damePublicacionesProducto($producto) {

		$query  = $this->createQueryBuilder('p');
     
		if ($producto) {
			$query->where('producto_id = $producto');
		}
		else {
			$query->where($query->expr()->isNull("p.producto"));
			$query->andWhere($query->expr()->isNotNull("p.brand"));
			$query->andWhere($query->expr()->isNotNull("p.model"));
		}

		$query->limit(2000);

		return $query->getQuery()->getResult();
	}

}
