<?php

namespace AppBundle\Repository;

/**
 * PublicacionEbayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionEbayRepository extends \Doctrine\ORM\EntityRepository
{
}
