<?php

namespace AppBundle\Repository;

/**
 * RelacionEspecificacionesPublicacionEbayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelacionEspecificacionesPublicacionEbayRepository extends \Doctrine\ORM\EntityRepository
{
}
