<?php

namespace AppBundle\Repository;

/**
 * ReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends \Doctrine\ORM\EntityRepository
{

	public function reservasPorTipo($tipo_id, $desde, $hasta) {

		$query  = $this->createQueryBuilder('r');
     
     	$query->select('count(r.id)');

		$query->where("r.fechaAlta > $desde");
		$query->andWhere("r.tipoDePago_1 = '$tipo_id'");

		if ($hasta ) {
			$query->andWhere("r.fechaAlta < $hasta");
		}

		return $query->getQuery()->getResult();
	}
}
