<?php

namespace AppBundle\Repository;

/**
 * SeleccionDeCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeleccionDeCompraRepository extends \Doctrine\ORM\EntityRepository
{
}
