<?php

namespace AppBundle\Repository;

/**
 * TipoDePagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDePagoRepository extends \Doctrine\ORM\EntityRepository
{
}
