<?php

namespace AppBundle\Repository;

/**
 * TipoDeEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDeEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
