<?php

namespace AppBundle\Repository;

/**
 * TipoDeCostoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDeCostoRepository extends \Doctrine\ORM\EntityRepository
{
}
