<?php

namespace AppBundle\Repository;

/**
 * TipoDeVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDeVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
