services:
    app.admin.publicacion_ml:
        class: AppBundle\Admin\PublicacionMLAdmin
        arguments: [~, AppBundle\Entity\PublicacionML, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: MercadoLibre, label: Publicaciones }
        public: true
        
    app.admin.busqueda_ebay:
        class: AppBundle\Admin\BusquedaEbayAdmin
        arguments: [~, AppBundle\Entity\BusquedaEbay, AppBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Ebay, label: BusquedaEbay }

    ebay_service:
        class:     AppBundle\Service\EbayService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }
    
    meli_service:
        class:     AppBundle\Service\MeliService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }

    compras_service:
        class:     AppBundle\Service\ComprasService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }

    productos_service:
        class:     AppBundle\Service\ProductosService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }
    cargas_service:
        class:     AppBundle\Service\CargasImportacionService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }

    app.admin.categoria_ebay:
        class: AppBundle\Admin\CategoriaEbayAdmin
        arguments: [~, AppBundle\Entity\CategoriaEbay, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Ebay, label: CategoriaEbay }

    app.admin.publicacion_ebay:
        class: AppBundle\Admin\PublicacionEbayAdmin
        arguments: [~, AppBundle\Entity\PublicacionEbay, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Ebay, label: PublicacionEbay, pager_type: simple }

    #app.admin.especificaciones_producto_ebay:
    #   class: AppBundle\Admin\EspecificacionesProductoEbayAdmin
    #    arguments: [~, AppBundle\Entity\EspecificacionesProductoEbay, SonataAdminBundle:CRUD]
    #    tags:
    #        - { name: sonata.admin, manager_type: orm, group: admin, label: EspecificacionesProductoEbay }

    app.admin.reserva:
        class: AppBundle\Admin\ReservaAdmin
        arguments: [~, AppBundle\Entity\Reserva, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestión, label: Reserva }
        public: true

    app.admin.cuenta:
        class: AppBundle\Admin\CuentaAdmin
        arguments: [~, AppBundle\Entity\Cuenta, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Datos estructurales, label: Cuenta }
        public: true

    app.admin.estado:
        class: AppBundle\Admin\EstadoAdmin
        arguments: [~, AppBundle\Entity\Estado, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Datos estructurales, label: Estado }
        public: true

    app.admin.producto:
        class: AppBundle\Admin\ProductoAdmin
        arguments: [~, AppBundle\Entity\Producto, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestión, label: Producto }
        public: true

    app.admin.seleccion_de_compra:
        class: AppBundle\Admin\SeleccionDeCompraAdmin
        arguments: [~, AppBundle\Entity\SeleccionDeCompra, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestión, label: Selección de compra }
        public: true

    app.admin.tipo_de_entrega:
        class: AppBundle\Admin\TipoDeEntregaAdmin
        arguments: [~, AppBundle\Entity\TipoDeEntrega, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Datos estructurales, label: TipoDeEntrega }
        public: true

    app.admin.tipo_de_pago:
        class: AppBundle\Admin\TipoDePagoAdmin
        arguments: [~, AppBundle\Entity\TipoDePago, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Datos estructurales, label: TipoDePago }
        public: true

    app.admin.tipo_de_venta:
        class: AppBundle\Admin\TipoDeVentaAdmin
        arguments: [~, AppBundle\Entity\TipoDeVenta, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Datos estructurales, label: TipoDeVenta }
        public: true

    app.admin.orden_de_compra:
        class: AppBundle\Admin\OrdenDeCompraAdmin
        arguments: [~, AppBundle\Entity\OrdenDeCompra, , AppBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestión, label: Orden de compra }
        public: true

    app.admin.carga_importacion:
        class: AppBundle\Admin\CargaImportacionAdmin
        arguments: [~, AppBundle\Entity\CargaImportacion, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestión, label: Cargas de importación }
        public: true

    app.admin.publicacion_ml:
        class: AppBundle\Admin\PublicacionMLAdmin
        arguments: [~, AppBundle\Entity\PublicacionML, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: MercadoLibre, label: Publicaciones }
        public: true
