services:
    app.admin.busqueda_ebay:
        class: AppBundle\Admin\BusquedaEbayAdmin
        arguments: [~, AppBundle\Entity\BusquedaEbay, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: BusquedaEbay }

    ebay_service:
        class:     AppBundle\Service\EbayService
        arguments: []

