services:
    app.admin.busqueda_ebay:
        class: AppBundle\Admin\BusquedaEbayAdmin
        arguments: [~, AppBundle\Entity\BusquedaEbay, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: BusquedaEbay }

    ebay_service:
        class:     AppBundle\Service\EbayService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }

    app.admin.producto:
        class: AppBundle\Admin\ProductoAdmin
        arguments: [~, AppBundle\Entity\Producto, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Producto }
