services:
    app.admin.busqueda_ebay:
        class: AppBundle\Admin\BusquedaEbayAdmin
        arguments: [~, AppBundle\Entity\BusquedaEbay, AppBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: BusquedaEbay }

    ebay_service:
        class:     AppBundle\Service\EbayService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }

    app.admin.categoria_ebay:
        class: AppBundle\Admin\CategoriaEbayAdmin
        arguments: [~, AppBundle\Entity\CategoriaEbay, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CategoriaEbay }

    app.admin.publicacion_ebay:
        class: AppBundle\Admin\PublicacionEbayAdmin
        arguments: [~, AppBundle\Entity\PublicacionEbay, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PublicacionEbay }
