<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BusquedaEbay extends \AppBundle\Entity\BusquedaEbay implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'vendedorEbayId', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'filtrarNew', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'precioMinimo', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'precioMaximo', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'categoria'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'vendedorEbayId', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'filtrarNew', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'precioMinimo', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'precioMaximo', '' . "\0" . 'AppBundle\\Entity\\BusquedaEbay' . "\0" . 'categoria'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BusquedaEbay $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendedorEbayId($vendedorEbayId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendedorEbayId', [$vendedorEbayId]);

        return parent::setVendedorEbayId($vendedorEbayId);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendedorEbayId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendedorEbayId', []);

        return parent::getVendedorEbayId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiltrarNew($filtrarNew)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiltrarNew', [$filtrarNew]);

        return parent::setFiltrarNew($filtrarNew);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiltrarNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiltrarNew', []);

        return parent::getFiltrarNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioMinimo($precioMinimo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioMinimo', [$precioMinimo]);

        return parent::setPrecioMinimo($precioMinimo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioMinimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioMinimo', []);

        return parent::getPrecioMinimo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioMaximo($precioMaximo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioMaximo', [$precioMaximo]);

        return parent::setPrecioMaximo($precioMaximo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioMaximo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioMaximo', []);

        return parent::getPrecioMaximo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

}
